# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MollyDiscordRelay < Formula
  desc "Discord relay server for terminal-native realtime chat"
  homepage "https://github.com/ploglabs/molly-discord-relay"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.2.0/molly-discord-relay_0.2.0_darwin_amd64.tar.gz"
      sha256 "472ec7160bf61452d6b786ff02203f93a83a0eaa6993093195d1f16a16b1f8bb"

      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.2.0/molly-discord-relay_0.2.0_darwin_arm64.tar.gz"
      sha256 "c8871670e797dd13dd8601277b510853e0808d94b43f2eb0d6a90b32176c7513"

      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.2.0/molly-discord-relay_0.2.0_linux_amd64.tar.gz"
      sha256 "0b4581c67526138277aff2857c056c4b6619642881f3e7f97ef7c2ad0e41c93d"
      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.2.0/molly-discord-relay_0.2.0_linux_arm64.tar.gz"
      sha256 "8162be7d96f29f0ec02561aadc876fb4203aa64df3c1d5aa1ac4699b2ef08bd6"
      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
  end
end
