# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Molly < Formula
  desc "Terminal-native realtime chat client for Discord"
  homepage "https://github.com/ploglabs/molly-terminal"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ploglabs/molly-terminal/releases/download/v0.2.10/molly-terminal_0.2.10_darwin_amd64.tar.gz"
      sha256 "485f3d4e894c002c1088f14a65426791f19437caa6a56c2735014a63627dae79"

      define_method(:install) do
        bin.install "molly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ploglabs/molly-terminal/releases/download/v0.2.10/molly-terminal_0.2.10_darwin_arm64.tar.gz"
      sha256 "5e323fe2e79518c8dcd5d5af05413205ec6018577b72b3f3f53510a39fc2b6dd"

      define_method(:install) do
        bin.install "molly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-terminal/releases/download/v0.2.10/molly-terminal_0.2.10_linux_amd64.tar.gz"
      sha256 "5b4d7d991249de651259ed81afa6345c798124d6255874eeb6c2e2d744efe6dd"
      define_method(:install) do
        bin.install "molly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-terminal/releases/download/v0.2.10/molly-terminal_0.2.10_linux_arm64.tar.gz"
      sha256 "7ddc1048a83828e5cdbd42b74c2db204a20bf4c548e5bf3eb4d7eb1e03e74ede"
      define_method(:install) do
        bin.install "molly"
      end
    end
  end

  test do
    system "#{bin}/molly", "--help"
  end
end
