# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MollyDiscordRelay < Formula
  desc "Discord relay server for terminal-native realtime chat"
  homepage "https://github.com/ploglabs/molly-discord-relay"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.1.1/molly-discord-relay_0.1.1_darwin_amd64.tar.gz"
      sha256 "b150d5371521e92b3ae8e34bf60d1c1f752c3ea661e415f6be3711051ab4760c"

      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.1.1/molly-discord-relay_0.1.1_darwin_arm64.tar.gz"
      sha256 "db31da47da9fa147b66011d9b736fb518adb65f65ffad0de34293bcf5b319b09"

      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.1.1/molly-discord-relay_0.1.1_linux_amd64.tar.gz"
      sha256 "6fe946820132de3229a5741487e14075171dd15efbedcf94da9aefdb7742ff58"
      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ploglabs/molly-discord-relay/releases/download/v0.1.1/molly-discord-relay_0.1.1_linux_arm64.tar.gz"
      sha256 "726537bc82134de85fd9a44ef50dd47364ade2d94496282015a4d14be14dacd5"
      define_method(:install) do
        bin.install "molly-discord-relay"
      end
    end
  end
end
